unique_ids:
  assets:
    standard-page.html: QHYFSULX5KE3N3CATDGKIBIMX4ANUGDW
    theme.css: SJ5VTMFW7Z373GDD3JWQD4AR6MKGZWYM
  forms:
    Inspect_1: 5RDZBEJEQ4XQOYLDNGUUFOBQYKXOQGDE
  modules: {}
  scripts: {}
  server_modules:
    ServerModule1: '1756909695675405517900544.46515'
